# pull official base image
FROM node:latest


WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

COPY package*.json ./
RUN npm install --silent
RUN npm install react-scripts@3.4.0 -g --silent
COPY . .

# RUN npm run build
EXPOSE 3000

# start app
CMD [ "npm", "start" ]
